# Generated by Django 4.1.1 on 2022-09-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0005_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like_users',
            field=models.ManyToManyField(null=True, related_name='mylikes', to='blogApp.account'),
        ),
    ]
