# Generated by Django 4.1.1 on 2022-09-25 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_post_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created',
        ),
    ]
