# Generated by Django 4.1.1 on 2022-09-26 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0006_alter_like_like_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like_users',
            field=models.ManyToManyField(related_name='mylikes', to='blogApp.account'),
        ),
    ]
